// "use client"
/** @jsxImportSource react */
import {StylesProvider} from "../useStyle"

import "../global.css"
// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
     
        <StylesProvider> {children}</StylesProvider>
        </body>
    </html>
  )
}
